"""SQLite connection and canonical schema-migration infrastructure."""

from .connection import connect_database
from .migration_ledger import initialize_migration_ledger
from .migrations import (
    MIGRATIONS,
    Migration,
    MigrationApplicationError,
    MigrationChecksumError,
    MigrationError,
    MigrationOrderError,
    apply_migrations,
)
from .repositories import (
    SQLiteClarificationRepository,
    SQLiteConstraintRepository,
    SQLiteContextPacketRepository,
    SQLiteConversationRepository,
    SQLiteConversationStateRepository,
    SQLiteEntityRepository,
    SQLiteEvaluationRepository,
    SQLiteInspectionSnapshotBoundary,
    SQLiteMemoryRepository,
    SQLiteMessageRepository,
    SQLiteModelCallRepository,
    SQLiteProcessingRunRepository,
    SQLiteProjectRepository,
    SQLiteReferenceResolutionRepository,
    SQLiteSettingsRepository,
    SQLiteTaskRepository,
    SQLiteTopicRepository,
    SQLiteTransactionBoundary,
    SQLiteValidationRepository,
)

__all__ = [
    "MIGRATIONS",
    "Migration",
    "MigrationApplicationError",
    "MigrationChecksumError",
    "MigrationError",
    "MigrationOrderError",
    "SQLiteClarificationRepository",
    "SQLiteConstraintRepository",
    "SQLiteContextPacketRepository",
    "SQLiteConversationRepository",
    "SQLiteConversationStateRepository",
    "SQLiteEntityRepository",
    "SQLiteEvaluationRepository",
    "SQLiteInspectionSnapshotBoundary",
    "SQLiteMemoryRepository",
    "SQLiteMessageRepository",
    "SQLiteModelCallRepository",
    "SQLiteProcessingRunRepository",
    "SQLiteProjectRepository",
    "SQLiteReferenceResolutionRepository",
    "SQLiteSettingsRepository",
    "SQLiteTaskRepository",
    "SQLiteTopicRepository",
    "SQLiteTransactionBoundary",
    "SQLiteValidationRepository",
    "apply_migrations",
    "connect_database",
    "initialize_migration_ledger",
]
