"""GUI-thread shell facade and immutable presentation values."""

from context_for_ai.ui.presentation import (
    ContextInspectionPageState,
    ContextInspectionPresentationView,
    ExecutionKind,
    ForegroundExecutionFailureView,
    ForegroundTerminalEnvelope,
    InspectionCollectionPresentation,
    InspectionExecutionFailureView,
    InspectionListItemPresentation,
    InspectionResultPresentation,
    InspectionScalarPresentation,
    InspectionSectionPresentation,
    InspectionTerminalEnvelope,
    ManualOperationKind,
    ManualOperationsExecutionFailureView,
    ManualOperationsTerminalEnvelope,
    MemoryPageState,
    MonotonicCancellationToken,
    ProjectsPageState,
    Route,
    SettingsApplyFailureView,
    SettingsPageState,
    ShellState,
    TerminalPresentationView,
    ValidationHistoryPageState,
)
from context_for_ai.ui.shell import ShellFacade
from context_for_ai.ui.startup import (
    NativeStartupErrorPresenter,
    StartupErrorPresenter,
    StartupFailureKind,
    StartupFailureView,
    StartupPresentationMode,
    safe_stderr_record,
    startup_failure_for_preparation,
)


__all__ = [
    "ExecutionKind",
    "ContextInspectionPageState",
    "ContextInspectionPresentationView",
    "ForegroundExecutionFailureView",
    "ForegroundTerminalEnvelope",
    "InspectionCollectionPresentation",
    "InspectionExecutionFailureView",
    "InspectionListItemPresentation",
    "InspectionResultPresentation",
    "InspectionScalarPresentation",
    "InspectionSectionPresentation",
    "InspectionTerminalEnvelope",
    "ManualOperationKind",
    "ManualOperationsExecutionFailureView",
    "ManualOperationsTerminalEnvelope",
    "MemoryPageState",
    "MonotonicCancellationToken",
    "NativeStartupErrorPresenter",
    "Route",
    "ProjectsPageState",
    "SettingsApplyFailureView",
    "SettingsPageState",
    "ShellFacade",
    "ShellState",
    "StartupErrorPresenter",
    "StartupFailureKind",
    "StartupFailureView",
    "StartupPresentationMode",
    "TerminalPresentationView",
    "ValidationHistoryPageState",
    "safe_stderr_record",
    "startup_failure_for_preparation",
]
